version: '3.1'
 
services:
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_DATABASE: smdb
      MYSQL_PASSWORD: hbstudent
      MYSQL_ROOT_PASSWORD: hbstudent
      MYSQL_ROOT_HOST: '%'
    volumes:
      - db-data:/var/lib/mysql
    restart: always
    networks:
      - backend 
  integration:
    depends_on:
      - mysql
    image: "smdb_api:test-B${BUILD_NUMBER}"
    build:
      context: api # Use an image built from the specified dockerfile in the `api` directory.
      dockerfile: Dockerfile.Tests
    ports:
      - "5000:5000" # Forward the exposed port 8080 on the container to port 8080 on the host machine
    restart: always
    environment: # Pass environment variables to the service
      - TEAMCITY_PROJECT_NAME
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/smdb?useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: hbstudent 
    networks:
      - backend 
volumes:
    db-data:
networks:
  backend: