version: '3.1'
 
services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_DATABASE: smdb
      MYSQL_USER: root
      MYSQL_PASSWORD: hbstudent
      DEBUG: 1
    volumes:
      - db-data:/var/lib/mysql
    restart: always
  integration:
    depends_on:
      - mysql
    image: "smdb_api:test-B${BUILD_NUMBER}"
    build:
      context: api # Use an image built from the specified dockerfile in the `api` directory.
      dockerfile: Dockerfile.Tests
    environment:
      - TEAMCITY_PROJECT_NAME
volumes:
    db-data: