version: '3.1'
 
services:
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_DATABASE: smdb
      MYSQL_PASSWORD: hbstudent
      MYSQL_ROOT_PASSWORD: hbstudent
      MYSQL_ROOT_HOST: '%'
    volumes:
      - db-data:/var/lib/mysql
    restart: always
    networks:
      - backend 
  integration:
    depends_on:
      - mysql
    image: "smdb_api:test-B${BUILD_NUMBER}"
    build:
      context: api # Use an image built from the specified dockerfile in the `api` directory.
      dockerfile: Dockerfile.Tests
    environment:
      - TEAMCITY_PROJECT_NAME
    networks:
      - backend 
volumes:
    db-data:
networks:
  backend: